### PR TITLE
Option to remove non permanent headers on redirects

### PR DESCRIPTION
**Pull request by hoffi**
New option "for_followed_redirect" (Default is "true") on Driver#add_header to remove temporary headers on a redirect.

### CODE REVIEW

**Comment by twalpole** [comment]
What's the use case for this?

**Comment by der-flo** [comment]
Glad you asked, I waited for the question.

In one of our Rails apps we have a splitted HTTP/HTTPS routing, the pages are only available via one protocol, not both. Poltergeist/Capybara provides no distinct HTTPS server, so every visit has to go to the standard HTTP server. An HTTP header `X-Forwarded-SSL` helps Rails with the routing decision.

So we provide two helper methods for our feature specs to annotate which clicks will result in HTTPS requests. Code says more than thousand words:

```ruby
module SslAnnotation
  def next_page_has_ssl_url
    page.driver.add_header('X-Forwarded-SSL', 'on', permanent: false)
  end

  def next_page_has_ssl_url_but_redirects_to_nonssl_url
    page.driver.add_header('X-Forwarded-SSL', 'on',
                           permanent: false, for_followed_redirect: false)
  end
RSpec.configuration.include(SslAnnotation)
```

If you request the target URL (HTTPS) and it redirects to a HTTP URL, Poltergeist requests this URL also with the configured header. This needs to get disabled with the `for_followed_redirect: false` option.

**Comment by twalpole** [comment]
This seems like a pretty specialized use case, I'm not sure it belongs in Poltergeist. You could probably implement your desired behavior through middleware added to your app in Capybara.  @route - thoughts?

**Comment by route** [comment]
@hoffi  Does `permanent: false` send headers to a redirected url and then removes them afterwards?

**Comment by hoffi** [comment]
Headers added with `permanent: false` are still there after a redirect.

The headers will only removed when i make a new request e.g. after i click on a link.

**Comment by route** [comment]
@twalpole While it looks like an edge case for me too they kinda complement `permanent: false`. I think I'm for it, maybe we should just remove a confusion with method options `permanent`, `for_followed_redirect`

**Comment by twalpole** [comment]
Ok -- so if we're going to go with this, the options are a problem since a user could specify-  `permanent: true, for_followed_redirect: false` - which is meaningless.  So I think we either need to error on invalid combinations or move it all under the permanent option -- maybe with allowed values of  `true, false, :no_redirect` or something?

**Comment by hoffi** [comment]
I think enhancing the `permanent` option would be easier to understand.

If this is ok for you we can change it.

**Comment by route** [comment]
@twalpole yea let's use yours combinations for permanent, I can't come up with anything else

**Comment by route** [comment]
@hoffi let's do it

**Comment by twalpole** [comment]
@hoffi Any change at an updated PR for this?  We need to release 1.14 soon to support the new  Capybara being released today or tomorrow and it could go into the release.

**Comment by svenwin** [comment]
👍

**Comment by hoffi** [comment]
@twalpole @route I have updated the code

**Comment by twalpole** [comment]
@hoffi Thanks -- Please squash the commits

**Comment by hoffi** [comment]
@twalpole the commits are squashed, can it be merged?

**Comment by route** [comment]
LGTM

**Pull request merged**
