### PR TITLE
move to travis conatiner based infrastructure

### PR DESCRIPTION
**Pull request by twalpole**

### CODE REVIEW

**Comment by route** [comment]
Weird it shows 1.9.8 for 2.0 job
http://take.ms/CDnMj

**Comment by twalpole** [comment]
Yeah, it's printing out the system version of phantomjs before the tests are run, but in the tests it's set to use the downloaded v2 - https://github.com/teampoltergeist/poltergeist/blob/25b59dd81c96c5338ba2ecd5551671c30c2064a9/spec/spec_helper.rb#L21

**Comment by route** [comment]
Yeah, one update from me then =) I tried to run 2.0.1 seems like it still has issues with attachments. Not sure if they fix them for a release. Looks like I saw a few more regressions. Unfortunately I'm on El Capitan now and it has problems with 2.0... How many failing test do you have for 2.0 on local machine?

**Comment by twalpole** [comment]
I'm still on Yosemite - Locally with 2.0.0 I get 18 failures,  11 are file attachment related (10 #attach_file, 1 Node#set) -  6 are window related - and then the 1 "Capybara::Session with poltergeist driver current_url supports allowed characters"  

I haven't really looked at the last one to see whats going on, or what it should be

**Comment by twalpole** [comment]
https://github.com/ariya/phantomjs/issues/12506   -- here is where the phantomjs team says the file upload  fix will be in 2.0.1 (last comment)

**Pull request merged**
