### PR TITLE
Disallow phantomjs 2

### PR DESCRIPTION
**Pull request by jonleighton**
See justification in commit message

cc @route @mikepack

### CODE REVIEW

**Comment by yaauie** [comment]
:+1: Makes sense, @jonleighton.

**Comment by mikepack** [comment]
I would not merge.

Without Phantom 2, poltergeist becomes unusable for driving modern web apps due to the old version of Webkit. Phantom 1 doesn't even support all of ES5.

Tests seem to run fine for me. I haven't run the poltergeist suite against Phantom 2, though, so that is a concern. I've built a Phantom 2 binary for Travis which would be a first step towards this.

It seems like disallowing Phantom 2 is not actually solving your teams problem, which is a lack of communication or tooling. Similar problems could happen if two developers are on different version of an operating system, different version of browser, different versions of anything. Tools like rvm and bundler ensure we're as consistent as we can be. Is the true solve something like this for poltergeist?

**Comment by tubbo** [comment]
> I haven't run the poltergeist suite against Phantom 2, though, so that is a concern.

@mikepack To be fair, I upgraded Poltergeist 1.6 in a gem here at my job and there didn't seem to be any random failures, but a few months later we saw some random regressions on feature specs in one of the Rails apps using that gem and implementing our platform. Downgrading to 1.9.8 seemed to fix the problem. Nothing changed in the tests except the poltergeist version. So even if you do run tests, you may not see the regression immediately.

But if you do want Poltergeist to run on the latest PhantomJS, why are you not testing your code against it?

**Comment by route** [comment]
I would be +1. There's a PR for instance which adds ability to work with alerts, confirms etc. and it crashes 1.9 but 2.0. My thoughts are create new branch put this functionality for alerts, relax phantomjs version, but lock it in master. When 2.x is come out and tested, merge it to master and lock on this or more version.

**Comment by route** [comment]
So for now 1.9 works unstable (I had a talk with Ariya) 2.0 is better but still has regressions. :)

**Comment by jonleighton** [comment]
> Tests seem to run fine for me. I haven't run the poltergeist suite against Phantom 2, though, so that is a concern. I've built a Phantom 2 binary for Travis which would be a first step towards this.

If Poltergeist's own tests pass against PhantomJS 2 then I am fine with allowing that version. If they do not then I don't think we should claim that Poltergeist supports PhantomJS 2. I don't know the answer to that question but it seems like that should be the fundamental deciding factor...

Either way I think it could be fine to have a "phantomjs2" branch which you can use in your Gemfile if you're happy with the potential risks.

**Comment by twalpole** [comment]
Poltergeist is now being tested against Phantomjs 2 on travis - and passing everything but Capybara's attach_file specs which phantomjs 2 is broken on.   We can probably close this PR.

**Comment by route** [comment]
Yeah +1 from me

**Pull request closed without merging**
