### PR TITLE
Support for URL whitelisting

### PR DESCRIPTION
**Pull request by justincase**
Initial support for URL whitelisting. It would be nice to have additional features as suggested in #600 but here's a first go at it.

/cc #588

### CODE REVIEW

**Comment by justincase** [comment]
Failure on RBX doesn't appear related to changes.

**Comment by route** [comment]
Oh great, thank you! Can you also add a changelog entry please?

**Comment by twalpole** [comment]
Currently in this pull being blacklisted overriders being whitelisted.  I think it should be the other way so that one can set   

    url_blacklist = ['']  #blacklist all urls
    url_whitelist = ['127.0.0.1']  # allow local urls

**Comment by twalpole** [comment]
Hmm -- actually I guess that is the behavior if the blacklist is just not set, and one sets the whitelist.   Maybe its fine as is

**Comment by justincase** [comment]
@route Will do!

@twalpole My reasoning is that you might want to whitelist a certain host e.g. `apiservice.com` but blacklist a specific endpoint like `apiservice.com/request/that/cost/money`. Either way you're correct that once the whitelist is set, all requests that aren't matched are blocked.

**Comment by twalpole** [comment]
@justincase When you've added the changelog entry please squash your commits, and then I think this will be good to merge

**Comment by route** [comment]
Any update on this?

**Comment by justincase** [comment]
@route Updated the changelog and squashed the commits.

**Comment by route** [comment]
Thanks, appreciate your contribution!

**Pull request merged**
