### PR TITLE
Change events should fire from the SELECT element, not the OPTION element.

### PR DESCRIPTION
**Pull request by jbaudanza**
This resolves issue #204.

This issue was also preventing onChange events in React from firing.

I recompiled the coffeescript. I must have a never version of coffeescript, because there are a lot of unrelated changes in the js output. The compilation step is in its own commit, so it can easily be rebased away if needed.

### CODE REVIEW

**Comment by McRip** [comment]
:+1: for merge.

**Comment by brissenden** [comment]
:+1: for merge as well

**Comment by mockdeep** [comment]
Just ran into this problem. Would be great to get it merged in. @jbaudanza looks like your pull needs to be rebased.

**Comment by jbaudanza** [comment]
I'm happy to rebase if I can get a thumbs up from one of the maintainers.

**Comment by route** [comment]
@jbaudanza It is definitely +1 so go ahead rebase and ping me again. Sorry limited on time but always answer if you mention me

**Comment by jbaudanza** [comment]
@route I've rebased and updated the spec a bit. 

There's still some unrelated failing specs, but are also failing on master for me.

**Comment by route** [comment]
Super, thanks for your time and sorry it took so long

**Pull request merged**
