### PR TITLE
add post method to browser

### PR DESCRIPTION
**Pull request by nathantsoi**
not sure why this doesnt exist? it's super useful for testing apis

call it with:

```
page.driver.browser.post 'https://mycoolwebsite/api.json', { email: TEST_EMAIL, password: TEST_PASSWORD }.to_query
```

### CODE REVIEW

**Comment by route** [comment]
Well while it's probably convenient method, it doesn't fit capybara because of the idea behind it. From capybara's README:
```
Capybara helps you test web applications by simulating how a real user would interact with your app. 
```
I don't know any way how real user can interact with a server except opening url(which is GET), clicking, submiting forms. That's the only reason why there's just one method `visit` which starts interaction with a site. BTW I don't see any reason why capybara with poltergeist should've been used for testing API, it's useful when there's JS on a page, not for API. You should probably use rack-test for this purpose.

**Comment by nathantsoi** [comment]
No worries, I figured there was a reason behind this. For testing non-rails
apps, is it possible to use rack-test for integration (feature) specs?

It would be awesome to expand the scope (and power) of poltergeist to
support "real users interacting with your app" even via api (ie. mobile
app).

Cheers,
N

**Comment by route** [comment]
@nathantsoi It is possible to use for rack-based(rails in particular) applications. Since we don't need JS runtime for XML/JSON/etc responces just switch capybara from poltergeist to rack-test driver and you'll see speed improvement.

**Comment by Paxa** [comment]
@route, Thank you for explanation, but this feature is useful for me.
I'm developing application that receive POST, another component redirect users to this app.

One more use case is testing security of forms, for example users has form to edit their profile, we may want to test scenario when user submit unexpected params, e.g. `user[is_admin]=1` or `user[id]=999`

So sad it's not merged

**Comment by route** [comment]
@Paxa I can be probably a bit out of context but since your entry point doesn't mean any user interaction with html or forms why don't you use rack-test for this purpose?

**Comment by Paxa** [comment]
Application itself not using ruby, also `rack-test` is very limited, no JS and real http requests

**Comment by route** [comment]
Could you please explain a bit more about your application like I said I'm out of the context so I could be wrong.

**Comment by Paxa** [comment]
I kinda agree with you: poltergeist is a driver for capybara, and suppose to do only actions that user can do with a browser. But in certain situations we may need something more, for example execute some javascript on page and send non-GET requests.

One more use case: If your every test case require user to login then you can send login form data directly - tests will run faster.

About my application is not so important: written in java, users come from other website where they submit form, so first request is POST with some parameters. I could simulate full behaviour in my tests: go to previous website and submit a form, but sending request directly is faster and easier

**Comment by Paxa** [comment]
Migrated to poltergeist 1.9 codebase https://github.com/Paxa/poltergeist/commit/2ef3d9c1d83185b495cfd4a77fe67af6f77cc794

**Comment by twalpole** [comment]
As explained previously, post doesn't fit into the purpose of Capybara and its drivers - locking

**Pull request closed without merging**
