### PR TITLE
WIP Support for PhantomJS 2.5.0

### PR DESCRIPTION
**Pull request by twalpole**
PhantomJS 2.5.0 currently has a beta release that has a few issues.  This is a work-in-progress for supporting 2.5.0 as it progresses.

### CODE REVIEW

**Comment by simi** [comment]
@twalpole I can setup CI to test against 2.5.0 beta also if needed.

**Comment by twalpole** [comment]
@simi That would be great -- I spent some time giving it a go on travis but the 2.5.0 beta binary isn't static yet so versions of libraries matter and I never got it working before giving up and just running the tests with it locally :)

**Comment by ashawley** [comment]
FWIW, I was able to get the beta to run in Travis for a related gem: colszowka/phantomjs-gem#97

**Comment by twalpole** [comment]
Closing this because the PJS 2.5.0 project was killed

**Pull request closed without merging**
