### PR TITLE
Test on Ruby 2.4.

### PR DESCRIPTION
**Pull request by connorshea**

### CODE REVIEW

**Comment by twalpole** [comment]
Ruby 2.4.0 has a nasty bug that causes random crashes if any of your code or gems used use delegators from forwardable.rb - https://bugs.ruby-lang.org/issues/13107 - I would recommend waiting for 2.4.1

**Comment by connorshea** [comment]
2.4.1 is out now :)

**Comment by twalpole** [comment]
@connorshea Yep - just not available on travis quite yet

**Comment by twalpole** [comment]
2.4.1 is no on travis - closing this in favor of 1eb4d37ebffa16f939a58794d0cf1c31abb2eb5f

**Comment by twalpole** [comment]
Thanks!

**Pull request closed without merging**
