### PR TITLE
drag by offset support

### PR DESCRIPTION
**Pull request by phoenixek12**
Dragging by offset suport at least for a native element. Drag to a position is not possible with poltergeist now

### CODE REVIEW

**Comment by phoenixek12** [comment]
I added tests for dragging ( I did not found a drag_by so I added it too :)
is ok like this?

Also I had to add -5 to the mouseUp event.. I dont understand why, but whitout it it moves by 5 more ( or less if negative direction ). Do you know what can cause it?

**Comment by phoenixek12** [comment]
Hey, @route is this acceptable? :) I would love to get it to new release if it would be possible.

**Comment by route** [comment]
@phoenixek12 Thanks for pinging me, yeah it looks good to me. You said there were issues with tests, how is it now?

**Comment by phoenixek12** [comment]
@route yeah, it is ok now, I wrote them and all passing.

**Comment by route** [comment]
I've merged it manually and added CHANGELOG entry. Thanks again!

**Pull request closed without merging**
