### PR TITLE
Fix a bunch of test failures, fix modals, and add PhantomJS2 to the travis build matrix

### PR DESCRIPTION
**Pull request by twalpole**
This fixes specs for Capybara 2.5 support and adds phantomjs 2 to the travis build matrix.  It also fixes the modals code that was reverted out a while ago to run without crashing under phantomjs1.9.8

* Add Node#path
* Fix events sent for modifier keys in send_keys
* Accept lowercase key symbols in send_keys
* Fix default_wait_time deprecation in Capybara
* Don't select disabled options
* Add PhantomJS 2.0.0 to the test matrix as an allowed failure
* Fix dragging test with PhantomJS 2 (can't use SVG - jquery doesn't support it)
* Fix scrolling test with PhantomJS 2
* Bring back the modals code and fix the crashing issues

PhantomJs 2 tests still fail due to the file upload issue that is supposed to be fixed when 2.0.1 releases and a current_url test -- not sure if that test is valid or not though

### CODE REVIEW

**Comment by route** [comment]
Oh my god! I just have no words because of this awesomeness! Big thanks to your work Thomas!

**Comment by route** [comment]
We have to release new version now! Yay! :)

**Comment by simi** [comment]
Amazing!!! :heart:  I have only one question. Why those two views were changed?

**Comment by twalpole** [comment]
@simi long page was changed because under phantomjs2 it would just wrap at viewport width so horizontal scrolling wasn't possible. I gave it width to stop that. Drag was changed because jquery doesn't support manipulating classes on svg elements properly, which means you can't use it for dragging svg elements in a browser that supports SVG (phantomjs 2) without adding something like jquery-svg. Easier to just change it rather than add another dependency

**Comment by simi** [comment]
That makes sense at all. Thanks for info @twalpole!

**Pull request merged**
