### PR TITLE
Support for modal (alerm/confirm/prompt) APIs.

### PR DESCRIPTION
**Pull request by gongo**
## Motivation

New pull-request of GH-266 .

:memo:  I used [znz:manipulate_dialog_boxes](https://github.com/znz/poltergeist/tree/manipulate_dialog_boxes) as reference. Thanks @znz !
## Remaining tasks

I think that remain some tasks to merge this branch to master. Example, Support Capybara 2.3.

Currently, this branch fail test for `window_xxx` APIs.
About these tests, I thought it would be resolved by GH-513.
So, I'm waiting merged this branch.

After merge GH-513,  I will do merged that branch to this branch, modify the test, and other tasks.

### CODE REVIEW

**Comment by route** [comment]
Hm this is causing lots of crashes like:
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/E16558C1-8B2E-4D57-876E-85B3A6463F1B.dmp
Have you seen them?

**Comment by gongo** [comment]
Hmm... I have never seen such error using `alart`, `confirm` and `prompt` .

**Comment by route** [comment]
That's getting interesting. So you run whole bunch of tests and see no crashes?

**Comment by gongo** [comment]
Sorry, when I try `rake test` now, crash occurred in my environment :bow:

**Comment by route** [comment]
I found out that it occured for the whole bunch of tests. It disappears when we add `driver.restart!` in `it` block of crashing test and run the whole suite. So it feels like `page.release` doesn't clean up properly and dump file needs to be analyzed :(

**Comment by vizcay** [comment]
Hi! What is the current status of this? I'm working with poltergeist 1.6.0, capybara 2.4.4 and phantomjs 1.9.2 and when I try for example:

```ruby
msg = page.accept_confirm do
  find('#show_alert').click
end
expect(msg).to eq 'this is an alert msg'
```
I get "Failure Capybara::NotSupportedByDriverError at Capybara::Driver::Base#accept_modal."

**Comment by route** [comment]
It's reverted since it causes segfaults on PhantomJS 1.9

**Comment by vizcay** [comment]
Where is the root problem lurking? PhantomJS, poltergeist or is unknown..

What about Poltergeist 2.0 ?

**Comment by mckinnsb** [comment]
Is there any more information surrounding this segfault? I have been using
this branch/modification successfully for nearly 6 months now and have not
had a crash.

**Comment by vizcay** [comment]
mcklnnsb: what branch are you using exaclty in your Gemfile?

I wan't to test in my environment if it segfaults..

**Comment by vizcay** [comment]
I fetched master this weekend, reverted c5cd330, downloaded and compiled PhantomJs 2.0 and configured my project Gemfile to see what happens in my feature specs (389 tests, ~ 7 mins running time).

Results:
- Not a single crash of phantomjs on multiple runs (10+).
- When testing multiple modal alerts in the same scenario, the second message is always wrong still filled with the first. I had to separate them and only one alert test per example (selenium worked fine).
- When running the entire test suit I sometimes get "false positives" with alert messages failing, basically alerts of other parts of the app that somehow appear there. I believe that some cleaunp is missing because of this "phantom messages of the past".
- When running the failings tests alone, they always pass. That leads into the "missing cleaunp" theory direction.
- I have one test that I cannot fix, but I think is not related to this: I have a function override that issues an event.stopInmediatePropagation() (that would display an alert) and instead displays another message. The message dialog is returning the message of the first in phantomjs but in selenium works fine.

I'm not exactly familiar with the poltergeist codebase, but if this won't affect other areas I will vote for adding this back to master, looks useful enough.

**Comment by mckinnsb** [comment]
Pablo, not trying to leave you hanging, I'll get back to you tomorrow with
the branch/versions I am using. Away from the box this weekend.

**Comment by mckinnsb** [comment]
Pablo, I am actually using my own fork/branch that I took out in July of
last year:

https://github.com/mckinnsb/poltergeist.git, the branch I am using is
"support_modal_apis".

**Comment by mckinnsb** [comment]
( sorry that took so long )11

**Comment by vizcay** [comment]
Thanks Stew, for my tests I've fetched master and reverted the commit c5cd330. My conclusion with phantomjs 2.0 are the same than yours, not a single crash, but still some minor bugs lurking.

**Comment by route** [comment]
We definitely need this feature but if we merge it we have to allow using just 2.0, since it has major bugs we cannot do it till they fixed

**Comment by vizcay** [comment]
Hi Dmitry, by major bugs you refer to the reported crashes or the other problems like the wrong messages?

In the first case, if the root cause is within phantomjs, and it's not a poltergeist fault (as it's looks like) why not just let it emit a warning if the modal API is called (or raise an exception) checking the phantomjs version to be > 2.0?

**Comment by route** [comment]
@vizcay Hi Pablo! When I last run tests suite on 2.0 there were a few major bugs like inability to upload file(attachments), selector problems and something else. Let me think over your idea.

**Comment by rquantz** [comment]
Hi all, thanks for your work on this. May I ask what the status is?

**Comment by nruth** [comment]
Should this be re-opened? Is there a branch people using 2.0 can point their gemfiles at?

**Comment by mckinnsb** [comment]
I've been using this version, from gongo's old PR:

https://github.com/mckinnsb/poltergeist

It's working well for me, but, I offer no guarantees for anyone else.

**Comment by twalpole** [comment]
@mckinnsb  This functionality has been in the official poltergeist since at least 1.7.0

**Pull request closed without merging**
