### PR TITLE
Tie command and response together with id

### PR DESCRIPTION
**Pull request by twalpole**
This ties commands and responses together with an id  -- should fix issues like #653 and #482.
@route  Please look over this as a sanity check and let me know your thoughts.

### CODE REVIEW

**Comment by route** [comment]
Sounds good to me as an idea! Need to go through the code!

**Comment by thiagogsr** [comment]
Hi guys, when will it merge?

**Comment by darthjee** [comment]
/me is very interested in this as well ^_^

**Comment by route** [comment]
I think we are good to go with this!

**Comment by route** [comment]
Thanks @twalpole !

**Comment by darthjee** [comment]
Thank you @twalpole !

**Pull request merged**
